name: Hello World

on:
  workflow_dispatch:

jobs:
  print-hello-id:
    name: Print Hello World
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        shell: bash
        run: echo "Hello World"